namespace Engine3D
{
    public enum AnimationType
    {
        Idle,
        Walk,
        WalkBack,
        Run,
        Jump,
        Flip,
        Jog,
        Dash,
        Roll,
        Crouch,
        Crouch_Walk,
        Limp,
        Drink,
        Stagger,
        JumpFall,
        SwordSlash,
        FireGun,
        PickaxeHit,
        ChopTree,
        UseTool,
        Sliding,
        JetPack,
        KnockedDownFront,
        LyingFront,
        KnockedDownBack,
        LyingBack,

        //Insect
        InsectIdle,
        InsectRun,
        InsectAttack,
        InsectJump,
        InsectFalling,
        InsectDie,

        //Insect heavy
        InsectHeavyIdle,
        InsectHeavyRun,
        InsectHeavyAttack,
        InsectHeavyJump,
        InsectHeavyFall,
        InsectHeavyDie,


        SpaceMarineIdle,
        SpaceMarineRifleIdle,
        SpaceMarinePistolIdle,
        SpaceMarineRifleIdleAlerted,
        SpaceMarinePistolIdleAlerted,
        SpaceMarineWalk,
        SpaceMarineRifleWalk,
        SpaceMarinePistolWalk,
        SpaceMarineWalkBackward,
        SpaceMarinePistolBackward,
        SpaceMarineRun,
        SpaceMarineRifleRun,
        SpaceMarineJump,
        SpaceMarineRifleJump,
        SpaceMarinePistolJump,
        SpaceMarineFlip,
        SpaceMarineRifleFlip,
        SpaceMarinePistolFlip,
        SpaceMarineJog,
        SpaceMarineRifleJog,
        SpaceMarinePistolJog,
        SpaceMarineDash,
        SpaceMarineRoll,
        SpaceMarineCrouch,
        SpaceMarineRifleCrouch,
        SpaceMarinePistolCrouch,
        SpaceMarineCrouch_Walk,
        SpaceMarineRifleCrouch_Walk,
        SpaceMarinePistolCrouch_Walk,
        SpaceMarineCrouch_WalkBackwards,
        SpaceMarineRifleCrouch_WalkBackwards,
        SpaceMarineLimp,
        SpaceMarineDrink,
        SpaceMarinePickaxeHit,
        SpaceMarineChoppingTree,
        SpaceMarineStagger,
        SpaceMarineJumpFall,
        SpaceMarineRifleJumpFall,
        SpaceMarinePistolJumpFall,
        SpaceMarineSwordSlash,
        SpaceMarineFireGun,
        SpaceMarineRifleFireGun,
        SpaceMarinePistolFireGun,
        SpaceMarineUseTool,
        SpaceMarineSliding,
        SpaceMarineJetPack,
        SpaceMarineKnockedDownFront,
        SpaceMarineLyingFront,
        SpaceMarineKnockedDownBack,
        SpaceMarineLyingBack,
        SpaceMarineSwordAttack_1,
        SpaceMarineSwordAttack_2,
        SpaceMarineSwordAttack_3,










        HumanLightIdle,
        HumanLightRifleIdle,
        HumanLightPistolIdle,
        HumanLightRifleIdleAlerted,
        HumanLightPistolIdleAlerted,
        HumanLightWalk,
        HumanLightRifleWalk,
        HumanLightPistolWalk,
        HumanLightWalkBackward,
        HumanLightPistolBackward,
        HumanLightRun,
        HumanLightRifleRun,
        HumanLightJump,
        HumanLightRifleJump,
        HumanLightPistolJump,
        HumanLightFlip,
        HumanLightRifleFlip,
        HumanLightPistolFlip,
        HumanLightJog,
        HumanLightRifleJog,
        HumanLightPistolJog,
        HumanLightDash,
        HumanLightRoll,
        HumanLightCrouch,
        HumanLightRifleCrouch,
        HumanLightPistolCrouch,
        HumanLightCrouch_Walk,
        HumanLightRifleCrouch_Walk,
        HumanLightPistolCrouch_Walk,
        HumanLightCrouch_WalkBackwards,
        HumanLightRifleCrouch_WalkBackwards,
        HumanLightLimp,
        HumanLightDrink,
        HumanLightPickaxeHit,
        HumanLightChoppingTree,
        HumanLightStagger,
        HumanLightJumpFall,
        HumanLightRifleJumpFall,
        HumanLightPistolJumpFall,
        HumanLightSwordSlash,
        HumanLightFireGun,
        HumanLightRifleFireGun,
        HumanLightPistolFireGun,
        HumanLightUseTool,
        HumanLightSliding,
        HumanLightJetPack,
        HumanLightKnockedDownFront,
        HumanLightLyingFront,
        HumanLightKnockedDownBack,
        HumanLightLyingBack,
        HumanLightSwordAttack_1,
        HumanLightSwordAttack_2,
        HumanLightSwordAttack_3,
    }
}