//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the behavior visual tool.
//     (Warning)Changes to this file may cause incorrect behavior, but it won't be lost.
// </auto-generated>
//-------
using Enums;
using KMath;
using System.Collections.Generic;
using AI.Sensor;

namespace AI
{
    public class MarineBehavior : BehaviorBase
    {
        public override BehaviorType Type { get { return BehaviorType.Marine; } }
        
        NodeInfo Root = new NodeInfo
        {
            index = 0,
            pos = new Vec2f(579.2f, 160.8704f),
            type = NodeType.DecoratorNode,
            children = new List<int>(){ 1}
        };

        NodeInfo Child1 = new NodeInfo
        {
            index = 1,
            pos = new Vec2f(579.2f, 268.0175f),
            type = NodeType.RepeaterNode,
            children = new List<int>(){ 2},
        };

        NodeInfo Child2 = new NodeInfo
        {
            index = 2,
            pos = new Vec2f(579.2f, 378.7431f),
            type = NodeType.SelectorNode,
            children = new List<int>(){ 10,  8},
        };

        NodeInfo Child3 = new NodeInfo
        {
            index = 3,
            pos = new Vec2f(283.3315f, 820.8f),
            type = NodeType.SequenceNode,
            children = new List<int>(){ 4,  5,  6},
        };

        NodeInfo Child4 = new NodeInfo
        {
            index = 4,
            pos = new Vec2f(133.6f, 950.2505f),
            type = NodeType.SelectClosestTarget,
            entriesID = new List<int>(){ 67108864}
        };

        NodeInfo Child5 = new NodeInfo
        {
            index = 5,
            pos = new Vec2f(284f, 950.4f),
            type = NodeType.ShootFireWeaponAction,
            entriesID = new List<int>(){ 67108864}
        };

        NodeInfo Child6 = new NodeInfo
        {
            index = 6,
            pos = new Vec2f(453.6001f, 950.4f),
            type = NodeType.WaitAction,
            entriesID = new List<int>(){ 50331648}
        };

        NodeInfo Child7 = new NodeInfo
        {
            index = 7,
            pos = new Vec2f(703.2001f, 730.4f),
            type = NodeType.WaitAction,
            children = new List<int>(){},
            entriesID = new List<int>(){ 50331648}
        };

        NodeInfo Child8 = new NodeInfo
        {
            index = 8,
            pos = new Vec2f(756.9475f, 585.7426f),
            type = NodeType.SequenceNode,
            children = new List<int>(){ 7,  9},
        };

        NodeInfo Child9 = new NodeInfo
        {
            index = 9,
            pos = new Vec2f(853.7722f, 730.3999f),
            type = NodeType.WaitAction,
            entriesID = new List<int>(){ 50331648}
        };

        NodeInfo Child10 = new NodeInfo
        {
            index = 10,
            pos = new Vec2f(453.6f, 496f),
            type = NodeType.ConditionalNode,
            children = new List<int>(){ 11},
            entriesID = new List<int>(){ 16777216}
        };

        NodeInfo Child11 = new NodeInfo
        {
            index = 11,
            pos = new Vec2f(453.5999f, 598.3209f),
            type = NodeType.SelectorNode,
            children = new List<int>(){ 12,  13},
        };

        NodeInfo Child12 = new NodeInfo
        {
            index = 12,
            pos = new Vec2f(284.1315f, 732f),
            type = NodeType.ConditionalNode,
            children = new List<int>(){ 3},
            entriesID = new List<int>(){ 16777217}
        };

        NodeInfo Child13 = new NodeInfo
        {
            index = 13,
            pos = new Vec2f(453.6001f, 732.0001f),
            type = NodeType.ReloadAction,
        };

        public override List<NodeInfo> Nodes
        {
            get
            {
                List<NodeInfo> nodes = new List<NodeInfo>();
                nodes.Add(Root);
                nodes.Add(Child1);
                nodes.Add(Child2);
                nodes.Add(Child3);
                nodes.Add(Child4);
                nodes.Add(Child5);
                nodes.Add(Child6);
                nodes.Add(Child7);
                nodes.Add(Child8);
                nodes.Add(Child9);
                nodes.Add(Child10);
                nodes.Add(Child11);
                nodes.Add(Child12);
                nodes.Add(Child13);
                return nodes;
            }
        }
        SensorEntity EnemySensorSensor = new SensorEntity
        {
            Type = SensorType.EnemySensor,
            EntriesID = new List<int>(){ 16777216}
        };
        SensorEntity BulletInClipSensor = new SensorEntity
        {
            Type = SensorType.BulletInClip,
            EntriesID = new List<int>(){ 16777217}
        };
      
        public override int SensorCount { get { return 2; } }

        public override SensorEntity[] Sensors
        {
            get
            {
                SensorEntity[] sensors = new SensorEntity[4];
                sensors[0] = EnemySensorSensor;
                sensors[1] = BulletInClipSensor;
                return sensors;
            }
        }

        BlackBoardModel.EntryInfo Entry0 = new BlackBoardModel.EntryInfo
        {
            Name = "Wait",
            Description = "",
            ID = 50331648
        };

        BlackBoardModel.EntryInfo Entry1 = new BlackBoardModel.EntryInfo
        {
            Name = "Target",
            Description = "",
            ID = 67108864
        };

        BlackBoardModel.EntryInfo Entry2 = new BlackBoardModel.EntryInfo
        {
            Name = "EnemiesInRange",
            Description = "",
            ID = 16777216
        };

        BlackBoardModel.EntryInfo Entry3 = new BlackBoardModel.EntryInfo
        {
            Name = "BulletsInClip",
            Description = "",
            ID = 16777217
        };
      
        public override BlackBoardModel AgentBlackboard
        {
            get
            {
                BlackBoardModel blackboard = new BlackBoardModel(Type);
                blackboard.Register(ref Entry0, (System.Int32)0);
                blackboard.Register(ref Entry1, new KMath.Vec2f(0f, 0f));
                blackboard.Register(ref Entry2, (System.Boolean)true);
                blackboard.Register(ref Entry3, (System.Boolean)true);
                return blackboard;
            }
        }
    };
}

