//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the behavior visual tool.
//     (Warning)Changes to this file may cause incorrect behavior, but it won't be lost.
// </auto-generated>
//-------
using Enums;
using KMath;
using System.Collections.Generic;
using AI.Sensor;

namespace AI
{
    public class PatrolBehavior : BehaviorBase
    {
        public override BehaviorType Type { get { return BehaviorType.Patrol; } }
        
        NodeInfo Root = new NodeInfo
        {
            index = 0,
            pos = new Vec2f(572.12f, 173.032f),
            type = NodeType.DecoratorNode,
        };

        public override List<NodeInfo> Nodes
        {
            get
            {
                List<NodeInfo> nodes = new List<NodeInfo>();
                nodes.Add(Root);
                return nodes;
            }
        }
      
        public override int SensorCount { get { return 0; } }

        public override SensorEntity[] Sensors
        {
            get
            {
                SensorEntity[] sensors = new SensorEntity[3];
                return sensors;
            }
        }
      
        public override BlackBoardModel AgentBlackboard
        {
            get
            {
                BlackBoardModel blackboard = new BlackBoardModel(Type);
                return blackboard;
            }
        }
    };
}

