namespace Enums.Tile
{
    public enum TileID
    {
        Error = 0,
        Air,
        Ore1, // 8
        Ore2,
        Ore3,
        Glass, // 9
        Moon, // 10
        Pipe,
        Background,
        Wire,
        Bedrock,
        Platform,
        Mech,
        Stone,
        SQNoSpecular_0,
        SQ_0,
        SQ_1,
        SQ_2,
        SQ_3,
        HSQNoSpecular_0,
        HSQNoSpecular_1,
        HSQNoSpecular_2,
        HSQNoSpecular_3,
        HSQ_0,
        HSQ_1,
        HSQ_2,
        HSQ_3,
        SSQ_0,
        SSQ_1,
        SSQ_2,
        SSQ_3,
        TI_0,
        TI_1,
        TI_2,
        TI_3,
        TO_0,
        TO_1,
        TO_2,
        TO_3,
        HTD_0,
        HTL_1,
        HTU_2,
        HTR_3,
        RHTD_0,
        RHTL_1,
        RHTU_2,
        RHTR_3,
        CSQ_0,
        CSQ_1,
        CSQ_2,
        CSQ_3,
        RCSQ_0,
        RCSQ_1,
        RCSQ_2,
        RCSQ_3,
    }
}