namespace KGUI
{
    public enum ElementEnums
    {
        Error = 0,
        
        Test,

        // Player Status HUD Indicators
        FoodIndicator,
        FuelIndicator,
        HealthIndicator,
        WaterIndicator,
        OxygenIndicator,

        // Placement Tool
        Bedrock,
        Dirt,
        Pipe,
        Wire,
        HealthPotion, // This we actually drink, not placing

        // Game Menu Buttons
        StartButton,
        ResumeButton,
        ControlsButton,
        ExitButton,

        // Geometry Tool
        SQNoSpecular_0Background,
        SQNoSpecular_0,
        SQ_0Background,
        SQ_0,
        SQ_1Background,
        SQ_1,
        SQ_2Background,
        SQ_2,
        SQ_3Background,
        SQ_3,
        HSQNoSpecular_0Background,
        HSQNoSpecular_0,
        HSQNoSpecular_1Background,
        HSQNoSpecular_1,
        HSQNoSpecular_2Background,
        HSQNoSpecular_2,
        HSQNoSpecular_3Background,
        HSQNoSpecular_3,
        HSQ_0Background,
        HSQ_0,
        HSQ_1Background,
        HSQ_1,
        HSQ_2Background,
        HSQ_2,
        HSQ_3Background,
        HSQ_3,
        SSQ_0Background,
        SSQ_0,
        SSQ_1Background,
        SSQ_1,
        SSQ_2Background,
        SSQ_2,
        SSQ_3Background,
        SSQ_3,
        TI_0Background,
        TI_0,
        TI_1Background,
        TI_1,
        TI_2Background,
        TI_2,
        TI_3Background,
        TI_3,
        TO_0Background,
        TO_0,
        TO_1Background,
        TO_1,
        TO_2Background,
        TO_2,
        TO_3Background,
        TO_3,
        HTD_0Background,
        HTD_0,
        HTL_1Background,
        HTL_1,
        HTU_2Background,
        HTU_2,
        HTR_3Background,
        HTR_3,
        RHTD_0Background,
        RHTD_0,
        RHTL_1Background,
        RHTL_1,
        RHTU_2Background,
        RHTU_2,
        RHTR_3Background,
        RHTR_3,
        CSQ_0Background,
        CSQ_0,
        CSQ_1Background,
        CSQ_1,
        CSQ_2Background,
        CSQ_2,
        CSQ_3Background,
        CSQ_3,
        RCSQ_0Background,
        RCSQ_0,
        RCSQ_1Background,
        RCSQ_1,
        RCSQ_2Background,
        RCSQ_2,
        RCSQ_3Background,
        RCSQ_3,
    }
}

