namespace Engine3D
{




    public enum AnimationType
    {
        Idle,
        Walk,
        WalkBack,
        Run,
        Jump,
        Flip,
        Jog,
        Dash,
        Roll,
        Crouch,
        Crouch_Walk,
        Limp,
        Drink,
        Stagger,
        JumpFall,
        SwordSlash, 
        FireGun,
        UseTool,
        Sliding,
        JetPack,
        KnockedDownFront,
        LyingFront,
        KnockedDownBack,
        LyingBack,

        //Insect
        InsectIdle,
        InsectRun,
        InsectAttack,
        InsectJump,
        InsectFalling,
        InsectDie,

        //Insect heavy
        InsectHeavyIdle,
        InsectHeavyRun,
        InsectHeavyAttack,
        InsectHeavyJump,
        InsectHeavyDie,


        SpaceMarineIdle,
        SpaceMarineRifleIdle,
        SpaceMarinePistolIdle,
        SpaceMarineRifleIdleAlerted,
        SpaceMarinePistolIdleAlerted,
        SpaceMarineWalk,
        SpaceMarineRifleWalk,
        SpaceMarinePistolWalk,
        SpaceMarineWalkBackward,
        SpaceMarinePistolBackward,
        SpaceMarineRun,
        SpaceMarineRifleRun,
        SpaceMarineJump,
        SpaceMarineRifleJump,
        SpaceMarinePistolJump,
        SpaceMarineFlip,
        SpaceMarineRifleFlip,
        SpaceMarinePistolFlip,
        SpaceMarineJog,
        SpaceMarineRifleJog,
        SpaceMarinePistolJog,
        SpaceMarineDash,
        SpaceMarineRoll,
        SpaceMarineCrouch,
        SpaceMarineRifleCrouch,
        SpaceMarinePistolCrouch,
        SpaceMarineCrouch_Walk,
        SpaceMarineRifleCrouch_Walk,
        SpaceMarinePistolCrouch_Walk,
        SpaceMarineLimp,
        SpaceMarineDrink,
        SpaceMarineStagger,
        SpaceMarineJumpFall,
        SpaceMarineRifleJumpFall,
        SpaceMarinePistolJumpFall,
        SpaceMarineSwordSlash, 
        SpaceMarineFireGun,
        SpaceMarineRifleFireGun,
        SpaceMarinePistolFireGun,
        SpaceMarineUseTool,
        SpaceMarineSliding,
        SpaceMarineJetPack,
        SpaceMarineKnockedDownFront,
        SpaceMarineLyingFront,
        SpaceMarineKnockedDownBack,
        SpaceMarineLyingBack,
    }
}